version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    context: ../
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  weather-app:
    build:
      context: ../
      dockerfile: build/docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8081:8080"
    restart: unless-stopped
    env_file:
      - ../.env

volumes:
  db_data:
    driver: local